<?php

declare(strict_types=1);

namespace App\Support;

/**
 * Lightweight geo reference data: countries (with their primary currency and
 * timezone, used for the country → currency/timezone cascade), currencies,
 * and IANA timezones. Codes match the storage format used across the app:
 * ISO 3166-1 alpha-2 country codes and ISO 4217 currency codes.
 */
final class Geo
{
    /**
     * @return list<array{code: string, name: string, currency: string, timezone: string}>
     */
    public static function countries(): array
    {
        $countries = [
            ['NG', 'Nigeria', 'NGN', 'Africa/Lagos'],
            ['GH', 'Ghana', 'GHS', 'Africa/Accra'],
            ['KE', 'Kenya', 'KES', 'Africa/Nairobi'],
            ['ZA', 'South Africa', 'ZAR', 'Africa/Johannesburg'],
            ['GB', 'United Kingdom', 'GBP', 'Europe/London'],
            ['US', 'United States', 'USD', 'America/New_York'],
            ['CA', 'Canada', 'CAD', 'America/Toronto'],
            ['EG', 'Egypt', 'EGP', 'Africa/Cairo'],
            ['DZ', 'Algeria', 'DZD', 'Africa/Algiers'],
            ['AO', 'Angola', 'AOA', 'Africa/Luanda'],
            ['BJ', 'Benin', 'XOF', 'Africa/Porto-Novo'],
            ['BW', 'Botswana', 'BWP', 'Africa/Gaborone'],
            ['BF', 'Burkina Faso', 'XOF', 'Africa/Ouagadougou'],
            ['BI', 'Burundi', 'BIF', 'Africa/Bujumbura'],
            ['CM', 'Cameroon', 'XAF', 'Africa/Douala'],
            ['CV', 'Cape Verde', 'CVE', 'Atlantic/Cape_Verde'],
            ['CF', 'Central African Republic', 'XAF', 'Africa/Bangui'],
            ['TD', 'Chad', 'XAF', 'Africa/Ndjamena'],
            ['KM', 'Comoros', 'KMF', 'Indian/Comoro'],
            ['CG', 'Congo (Brazzaville)', 'XAF', 'Africa/Brazzaville'],
            ['CD', 'Congo (Kinshasa)', 'CDF', 'Africa/Kinshasa'],
            ['CI', "Côte d'Ivoire", 'XOF', 'Africa/Abidjan'],
            ['DJ', 'Djibouti', 'DJF', 'Africa/Djibouti'],
            ['GQ', 'Equatorial Guinea', 'XAF', 'Africa/Malabo'],
            ['ER', 'Eritrea', 'ERN', 'Africa/Asmara'],
            ['SZ', 'Eswatini', 'SZL', 'Africa/Mbabane'],
            ['ET', 'Ethiopia', 'ETB', 'Africa/Addis_Ababa'],
            ['GA', 'Gabon', 'XAF', 'Africa/Libreville'],
            ['GM', 'Gambia', 'GMD', 'Africa/Banjul'],
            ['GN', 'Guinea', 'GNF', 'Africa/Conakry'],
            ['GW', 'Guinea-Bissau', 'XOF', 'Africa/Bissau'],
            ['LS', 'Lesotho', 'LSL', 'Africa/Maseru'],
            ['LR', 'Liberia', 'LRD', 'Africa/Monrovia'],
            ['LY', 'Libya', 'LYD', 'Africa/Tripoli'],
            ['MG', 'Madagascar', 'MGA', 'Indian/Antananarivo'],
            ['MW', 'Malawi', 'MWK', 'Africa/Blantyre'],
            ['ML', 'Mali', 'XOF', 'Africa/Bamako'],
            ['MR', 'Mauritania', 'MRU', 'Africa/Nouakchott'],
            ['MU', 'Mauritius', 'MUR', 'Indian/Mauritius'],
            ['MA', 'Morocco', 'MAD', 'Africa/Casablanca'],
            ['MZ', 'Mozambique', 'MZN', 'Africa/Maputo'],
            ['NA', 'Namibia', 'NAD', 'Africa/Windhoek'],
            ['NE', 'Niger', 'XOF', 'Africa/Niamey'],
            ['RW', 'Rwanda', 'RWF', 'Africa/Kigali'],
            ['ST', 'São Tomé and Príncipe', 'STN', 'Africa/Sao_Tome'],
            ['SN', 'Senegal', 'XOF', 'Africa/Dakar'],
            ['SC', 'Seychelles', 'SCR', 'Indian/Mahe'],
            ['SL', 'Sierra Leone', 'SLE', 'Africa/Freetown'],
            ['SO', 'Somalia', 'SOS', 'Africa/Mogadishu'],
            ['SS', 'South Sudan', 'SSP', 'Africa/Juba'],
            ['SD', 'Sudan', 'SDG', 'Africa/Khartoum'],
            ['TZ', 'Tanzania', 'TZS', 'Africa/Dar_es_Salaam'],
            ['TG', 'Togo', 'XOF', 'Africa/Lome'],
            ['TN', 'Tunisia', 'TND', 'Africa/Tunis'],
            ['UG', 'Uganda', 'UGX', 'Africa/Kampala'],
            ['ZM', 'Zambia', 'ZMW', 'Africa/Lusaka'],
            ['ZW', 'Zimbabwe', 'ZWL', 'Africa/Harare'],
            ['IE', 'Ireland', 'EUR', 'Europe/Dublin'],
            ['FR', 'France', 'EUR', 'Europe/Paris'],
            ['DE', 'Germany', 'EUR', 'Europe/Berlin'],
            ['ES', 'Spain', 'EUR', 'Europe/Madrid'],
            ['IT', 'Italy', 'EUR', 'Europe/Rome'],
            ['PT', 'Portugal', 'EUR', 'Europe/Lisbon'],
            ['NL', 'Netherlands', 'EUR', 'Europe/Amsterdam'],
            ['BE', 'Belgium', 'EUR', 'Europe/Brussels'],
            ['CH', 'Switzerland', 'CHF', 'Europe/Zurich'],
            ['SE', 'Sweden', 'SEK', 'Europe/Stockholm'],
            ['NO', 'Norway', 'NOK', 'Europe/Oslo'],
            ['DK', 'Denmark', 'DKK', 'Europe/Copenhagen'],
            ['FI', 'Finland', 'EUR', 'Europe/Helsinki'],
            ['PL', 'Poland', 'PLN', 'Europe/Warsaw'],
            ['AT', 'Austria', 'EUR', 'Europe/Vienna'],
            ['GR', 'Greece', 'EUR', 'Europe/Athens'],
            ['RU', 'Russia', 'RUB', 'Europe/Moscow'],
            ['TR', 'Türkiye', 'TRY', 'Europe/Istanbul'],
            ['UA', 'Ukraine', 'UAH', 'Europe/Kyiv'],
            ['AE', 'United Arab Emirates', 'AED', 'Asia/Dubai'],
            ['SA', 'Saudi Arabia', 'SAR', 'Asia/Riyadh'],
            ['QA', 'Qatar', 'QAR', 'Asia/Qatar'],
            ['KW', 'Kuwait', 'KWD', 'Asia/Kuwait'],
            ['IL', 'Israel', 'ILS', 'Asia/Jerusalem'],
            ['IN', 'India', 'INR', 'Asia/Kolkata'],
            ['PK', 'Pakistan', 'PKR', 'Asia/Karachi'],
            ['BD', 'Bangladesh', 'BDT', 'Asia/Dhaka'],
            ['CN', 'China', 'CNY', 'Asia/Shanghai'],
            ['HK', 'Hong Kong', 'HKD', 'Asia/Hong_Kong'],
            ['JP', 'Japan', 'JPY', 'Asia/Tokyo'],
            ['KR', 'South Korea', 'KRW', 'Asia/Seoul'],
            ['SG', 'Singapore', 'SGD', 'Asia/Singapore'],
            ['MY', 'Malaysia', 'MYR', 'Asia/Kuala_Lumpur'],
            ['ID', 'Indonesia', 'IDR', 'Asia/Jakarta'],
            ['TH', 'Thailand', 'THB', 'Asia/Bangkok'],
            ['VN', 'Vietnam', 'VND', 'Asia/Ho_Chi_Minh'],
            ['PH', 'Philippines', 'PHP', 'Asia/Manila'],
            ['AU', 'Australia', 'AUD', 'Australia/Sydney'],
            ['NZ', 'New Zealand', 'NZD', 'Pacific/Auckland'],
            ['BR', 'Brazil', 'BRL', 'America/Sao_Paulo'],
            ['AR', 'Argentina', 'ARS', 'America/Argentina/Buenos_Aires'],
            ['MX', 'Mexico', 'MXN', 'America/Mexico_City'],
            ['CL', 'Chile', 'CLP', 'America/Santiago'],
            ['CO', 'Colombia', 'COP', 'America/Bogota'],
            ['PE', 'Peru', 'PEN', 'America/Lima'],
            ['AD', 'Andorra', 'EUR', 'Europe/Andorra'],
            ['AF', 'Afghanistan', 'AFN', 'Asia/Kabul'],
            ['AG', 'Antigua & Barbuda', 'XCD', 'America/Antigua'],
            ['AI', 'Anguilla', 'XCD', 'America/Anguilla'],
            ['AL', 'Albania', 'ALL', 'Europe/Tirane'],
            ['AM', 'Armenia', 'AMD', 'Asia/Yerevan'],
            ['AQ', 'Antarctica', 'XXX', 'Antarctica/Casey'],
            ['AS', 'American Samoa', 'USD', 'Pacific/Pago_Pago'],
            ['AW', 'Aruba', 'AWG', 'America/Aruba'],
            ['AX', 'Åland Islands', 'EUR', 'Europe/Mariehamn'],
            ['AZ', 'Azerbaijan', 'AZN', 'Asia/Baku'],
            ['BA', 'Bosnia & Herzegovina', 'BAM', 'Europe/Sarajevo'],
            ['BB', 'Barbados', 'BBD', 'America/Barbados'],
            ['BG', 'Bulgaria', 'BGN', 'Europe/Sofia'],
            ['BH', 'Bahrain', 'BHD', 'Asia/Bahrain'],
            ['BL', 'St. Barthélemy', 'EUR', 'America/St_Barthelemy'],
            ['BM', 'Bermuda', 'BMD', 'Atlantic/Bermuda'],
            ['BN', 'Brunei', 'BND', 'Asia/Brunei'],
            ['BO', 'Bolivia', 'BOB', 'America/La_Paz'],
            ['BQ', 'Caribbean Netherlands', 'USD', 'America/Kralendijk'],
            ['BS', 'Bahamas', 'BSD', 'America/Nassau'],
            ['BT', 'Bhutan', 'BTN', 'Asia/Thimphu'],
            ['BV', 'Bouvet Island', 'NOK', 'Europe/Oslo'],
            ['BY', 'Belarus', 'BYN', 'Europe/Minsk'],
            ['BZ', 'Belize', 'BZD', 'America/Belize'],
            ['CC', 'Cocos (Keeling) Islands', 'AUD', 'Indian/Cocos'],
            ['CK', 'Cook Islands', 'NZD', 'Pacific/Rarotonga'],
            ['CR', 'Costa Rica', 'CRC', 'America/Costa_Rica'],
            ['CU', 'Cuba', 'CUP', 'America/Havana'],
            ['CW', 'Curaçao', 'XCG', 'America/Curacao'],
            ['CX', 'Christmas Island', 'AUD', 'Indian/Christmas'],
            ['CY', 'Cyprus', 'EUR', 'Asia/Nicosia'],
            ['CZ', 'Czechia', 'CZK', 'Europe/Prague'],
            ['DM', 'Dominica', 'XCD', 'America/Dominica'],
            ['DO', 'Dominican Republic', 'DOP', 'America/Santo_Domingo'],
            ['EC', 'Ecuador', 'USD', 'America/Guayaquil'],
            ['EE', 'Estonia', 'EUR', 'Europe/Tallinn'],
            ['EH', 'Western Sahara', 'MAD', 'Africa/El_Aaiun'],
            ['FJ', 'Fiji', 'FJD', 'Pacific/Fiji'],
            ['FK', 'Falkland Islands', 'FKP', 'Atlantic/Stanley'],
            ['FM', 'Micronesia', 'USD', 'Pacific/Pohnpei'],
            ['FO', 'Faroe Islands', 'DKK', 'Atlantic/Faroe'],
            ['GD', 'Grenada', 'XCD', 'America/Grenada'],
            ['GE', 'Georgia', 'GEL', 'Asia/Tbilisi'],
            ['GF', 'French Guiana', 'EUR', 'America/Cayenne'],
            ['GG', 'Guernsey', 'GBP', 'Europe/Guernsey'],
            ['GI', 'Gibraltar', 'GIP', 'Europe/Gibraltar'],
            ['GL', 'Greenland', 'DKK', 'America/Nuuk'],
            ['GP', 'Guadeloupe', 'EUR', 'America/Guadeloupe'],
            ['GS', 'South Georgia & South Sandwich Islands', 'GBP', 'Atlantic/South_Georgia'],
            ['GT', 'Guatemala', 'GTQ', 'America/Guatemala'],
            ['GU', 'Guam', 'USD', 'Pacific/Guam'],
            ['GY', 'Guyana', 'GYD', 'America/Guyana'],
            ['HM', 'Heard & McDonald Islands', 'AUD', 'Indian/Kerguelen'],
            ['HN', 'Honduras', 'HNL', 'America/Tegucigalpa'],
            ['HR', 'Croatia', 'EUR', 'Europe/Zagreb'],
            ['HT', 'Haiti', 'HTG', 'America/Port-au-Prince'],
            ['HU', 'Hungary', 'HUF', 'Europe/Budapest'],
            ['IM', 'Isle of Man', 'GBP', 'Europe/Isle_of_Man'],
            ['IO', 'British Indian Ocean Territory', 'USD', 'Indian/Chagos'],
            ['IQ', 'Iraq', 'IQD', 'Asia/Baghdad'],
            ['IR', 'Iran', 'IRR', 'Asia/Tehran'],
            ['IS', 'Iceland', 'ISK', 'Atlantic/Reykjavik'],
            ['JE', 'Jersey', 'GBP', 'Europe/Jersey'],
            ['JM', 'Jamaica', 'JMD', 'America/Jamaica'],
            ['JO', 'Jordan', 'JOD', 'Asia/Amman'],
            ['KG', 'Kyrgyzstan', 'KGS', 'Asia/Bishkek'],
            ['KH', 'Cambodia', 'KHR', 'Asia/Phnom_Penh'],
            ['KI', 'Kiribati', 'AUD', 'Pacific/Tarawa'],
            ['KN', 'St. Kitts & Nevis', 'XCD', 'America/St_Kitts'],
            ['KP', 'North Korea', 'KPW', 'Asia/Pyongyang'],
            ['KY', 'Cayman Islands', 'KYD', 'America/Cayman'],
            ['KZ', 'Kazakhstan', 'KZT', 'Asia/Almaty'],
            ['LA', 'Laos', 'LAK', 'Asia/Vientiane'],
            ['LB', 'Lebanon', 'LBP', 'Asia/Beirut'],
            ['LC', 'St. Lucia', 'XCD', 'America/St_Lucia'],
            ['LI', 'Liechtenstein', 'CHF', 'Europe/Vaduz'],
            ['LK', 'Sri Lanka', 'LKR', 'Asia/Colombo'],
            ['LT', 'Lithuania', 'EUR', 'Europe/Vilnius'],
            ['LU', 'Luxembourg', 'EUR', 'Europe/Luxembourg'],
            ['LV', 'Latvia', 'EUR', 'Europe/Riga'],
            ['MC', 'Monaco', 'EUR', 'Europe/Monaco'],
            ['MD', 'Moldova', 'MDL', 'Europe/Chisinau'],
            ['ME', 'Montenegro', 'EUR', 'Europe/Podgorica'],
            ['MF', 'St. Martin', 'EUR', 'America/Marigot'],
            ['MH', 'Marshall Islands', 'USD', 'Pacific/Majuro'],
            ['MK', 'North Macedonia', 'MKD', 'Europe/Skopje'],
            ['MM', 'Myanmar (Burma)', 'MMK', 'Asia/Yangon'],
            ['MN', 'Mongolia', 'MNT', 'Asia/Ulaanbaatar'],
            ['MO', 'Macao SAR China', 'MOP', 'Asia/Macau'],
            ['MP', 'Northern Mariana Islands', 'USD', 'Pacific/Saipan'],
            ['MQ', 'Martinique', 'EUR', 'America/Martinique'],
            ['MS', 'Montserrat', 'XCD', 'America/Montserrat'],
            ['MT', 'Malta', 'EUR', 'Europe/Malta'],
            ['MV', 'Maldives', 'MVR', 'Indian/Maldives'],
            ['NC', 'New Caledonia', 'XPF', 'Pacific/Noumea'],
            ['NF', 'Norfolk Island', 'AUD', 'Pacific/Norfolk'],
            ['NI', 'Nicaragua', 'NIO', 'America/Managua'],
            ['NP', 'Nepal', 'NPR', 'Asia/Kathmandu'],
            ['NR', 'Nauru', 'AUD', 'Pacific/Nauru'],
            ['NU', 'Niue', 'NZD', 'Pacific/Niue'],
            ['OM', 'Oman', 'OMR', 'Asia/Muscat'],
            ['PA', 'Panama', 'PAB', 'America/Panama'],
            ['PF', 'French Polynesia', 'XPF', 'Pacific/Tahiti'],
            ['PG', 'Papua New Guinea', 'PGK', 'Pacific/Port_Moresby'],
            ['PM', 'St. Pierre & Miquelon', 'EUR', 'America/Miquelon'],
            ['PN', 'Pitcairn Islands', 'NZD', 'Pacific/Pitcairn'],
            ['PR', 'Puerto Rico', 'USD', 'America/Puerto_Rico'],
            ['PS', 'Palestinian Territories', 'ILS', 'Asia/Gaza'],
            ['PW', 'Palau', 'USD', 'Pacific/Palau'],
            ['PY', 'Paraguay', 'PYG', 'America/Asuncion'],
            ['RE', 'Réunion', 'EUR', 'Indian/Reunion'],
            ['RO', 'Romania', 'RON', 'Europe/Bucharest'],
            ['RS', 'Serbia', 'RSD', 'Europe/Belgrade'],
            ['SB', 'Solomon Islands', 'SBD', 'Pacific/Guadalcanal'],
            ['SH', 'St. Helena', 'SHP', 'Atlantic/St_Helena'],
            ['SI', 'Slovenia', 'EUR', 'Europe/Ljubljana'],
            ['SJ', 'Svalbard & Jan Mayen', 'NOK', 'Arctic/Longyearbyen'],
            ['SK', 'Slovakia', 'EUR', 'Europe/Bratislava'],
            ['SM', 'San Marino', 'EUR', 'Europe/San_Marino'],
            ['SR', 'Suriname', 'SRD', 'America/Paramaribo'],
            ['SV', 'El Salvador', 'USD', 'America/El_Salvador'],
            ['SX', 'Sint Maarten', 'XCG', 'America/Lower_Princes'],
            ['SY', 'Syria', 'SYP', 'Asia/Damascus'],
            ['TC', 'Turks & Caicos Islands', 'USD', 'America/Grand_Turk'],
            ['TF', 'French Southern Territories', 'EUR', 'Indian/Kerguelen'],
            ['TJ', 'Tajikistan', 'TJS', 'Asia/Dushanbe'],
            ['TK', 'Tokelau', 'NZD', 'Pacific/Fakaofo'],
            ['TL', 'Timor-Leste', 'USD', 'Asia/Dili'],
            ['TM', 'Turkmenistan', 'TMT', 'Asia/Ashgabat'],
            ['TO', 'Tonga', 'TOP', 'Pacific/Tongatapu'],
            ['TT', 'Trinidad & Tobago', 'TTD', 'America/Port_of_Spain'],
            ['TV', 'Tuvalu', 'AUD', 'Pacific/Funafuti'],
            ['TW', 'Taiwan', 'TWD', 'Asia/Taipei'],
            ['UM', 'U.S. Outlying Islands', 'USD', 'Pacific/Midway'],
            ['UY', 'Uruguay', 'UYU', 'America/Montevideo'],
            ['UZ', 'Uzbekistan', 'UZS', 'Asia/Tashkent'],
            ['VA', 'Vatican City', 'EUR', 'Europe/Vatican'],
            ['VC', 'St. Vincent & Grenadines', 'XCD', 'America/St_Vincent'],
            ['VE', 'Venezuela', 'VES', 'America/Caracas'],
            ['VG', 'British Virgin Islands', 'USD', 'America/Tortola'],
            ['VI', 'U.S. Virgin Islands', 'USD', 'America/St_Thomas'],
            ['VU', 'Vanuatu', 'VUV', 'Pacific/Efate'],
            ['WF', 'Wallis & Futuna', 'XPF', 'Pacific/Wallis'],
            ['WS', 'Samoa', 'WST', 'Pacific/Apia'],
            ['YE', 'Yemen', 'YER', 'Asia/Aden'],
            ['YT', 'Mayotte', 'EUR', 'Indian/Mayotte'],
        ];

        $countries = array_map(
            static fn (array $c): array => ['code' => $c[0], 'name' => $c[1], 'currency' => $c[2], 'timezone' => $c[3]],
            $countries,
        );

        usort($countries, static fn (array $a, array $b): int => strcasecmp($a['name'], $b['name']));

        return $countries;
    }

    /**
     * @return array<string, string> ISO 4217 code => display name
     */
    public static function currencies(): array
    {
        $currencies = [
            'NGN' => 'Nigerian Naira (₦)', 'USD' => 'US Dollar ($)', 'EUR' => 'Euro (€)', 'GBP' => 'British Pound (£)',
            'GHS' => 'Ghanaian Cedi (₵)', 'KES' => 'Kenyan Shilling', 'ZAR' => 'South African Rand', 'CAD' => 'Canadian Dollar',
            'AUD' => 'Australian Dollar', 'NZD' => 'New Zealand Dollar', 'CHF' => 'Swiss Franc', 'CNY' => 'Chinese Yuan',
            'JPY' => 'Japanese Yen', 'INR' => 'Indian Rupee', 'AED' => 'UAE Dirham', 'SAR' => 'Saudi Riyal',
            'QAR' => 'Qatari Riyal', 'KWD' => 'Kuwaiti Dinar', 'EGP' => 'Egyptian Pound', 'MAD' => 'Moroccan Dirham',
            'DZD' => 'Algerian Dinar', 'TND' => 'Tunisian Dinar', 'XOF' => 'West African CFA Franc', 'XAF' => 'Central African CFA Franc',
            'TZS' => 'Tanzanian Shilling', 'UGX' => 'Ugandan Shilling', 'RWF' => 'Rwandan Franc', 'ZMW' => 'Zambian Kwacha',
            'BWP' => 'Botswana Pula', 'MZN' => 'Mozambican Metical', 'NAD' => 'Namibian Dollar', 'MUR' => 'Mauritian Rupee',
            'ETB' => 'Ethiopian Birr', 'SLE' => 'Sierra Leonean Leone', 'LRD' => 'Liberian Dollar', 'GMD' => 'Gambian Dalasi',
            'AOA' => 'Angolan Kwanza', 'CDF' => 'Congolese Franc', 'SEK' => 'Swedish Krona', 'NOK' => 'Norwegian Krone',
            'DKK' => 'Danish Krone', 'PLN' => 'Polish Złoty', 'RUB' => 'Russian Ruble', 'TRY' => 'Turkish Lira',
            'UAH' => 'Ukrainian Hryvnia', 'ILS' => 'Israeli Shekel', 'PKR' => 'Pakistani Rupee', 'BDT' => 'Bangladeshi Taka',
            'HKD' => 'Hong Kong Dollar', 'KRW' => 'South Korean Won', 'SGD' => 'Singapore Dollar', 'MYR' => 'Malaysian Ringgit',
            'IDR' => 'Indonesian Rupiah', 'THB' => 'Thai Baht', 'VND' => 'Vietnamese Đồng', 'PHP' => 'Philippine Peso',
            'BRL' => 'Brazilian Real', 'ARS' => 'Argentine Peso', 'MXN' => 'Mexican Peso', 'CLP' => 'Chilean Peso',
            'COP' => 'Colombian Peso', 'PEN' => 'Peruvian Sol',
        ];

        foreach (self::countries() as $country) {
            $currencies[$country['currency']] ??= $country['currency'];
        }

        ksort($currencies);

        return $currencies;
    }

    /**
     * @return list<string> IANA timezone identifiers
     */
    public static function timezones(): array
    {
        return \DateTimeZone::listIdentifiers();
    }
}
